version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ismogged
      - MYSQL_PASSWORD=secret
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=root:secret@tcp(mysql:3306)/ismogged?parseTime=true
    depends_on:
      - mysql
    entrypoint: [ "/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh"]
    command: [ "/app/main" ]
