CREATE TABLE `stock_exercise` (
	`id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) UNIQUE NOT NULL,
	`muscle_group` VARCHAR(20) NOT NULL,
	`category` VARCHAR(20) NOT NULL
);
