DROP TABLE IF EXISTS lift;
DROP TABLE IF EXISTS workout;
DROP TABLE IF EXISTS template;
DROP TABLE IF EXISTS exercise;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS muscle_group;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS user;
