// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: exercise.sql

package db

import (
	"context"
	"database/sql"
)

const createExercise = `-- name: CreateExercise :execlastid
INSERT INTO exercise (
	name,
	muscle_group,
	category,
	user_id
) VALUES (
	?,
	?,
	?,
	UUID_TO_BIN(?)
)
`

type CreateExerciseParams struct {
	Name        string `json:"name"`
	MuscleGroup string `json:"muscle_group"`
	Category    string `json:"category"`
	UserID      string `json:"user_id"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (int64, error) {
	result, err := q.exec(ctx, q.createExerciseStmt, createExercise,
		arg.Name,
		arg.MuscleGroup,
		arg.Category,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercise
WHERE id = ? AND user_id = UUID_TO_BIN(?)
`

type DeleteExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.exec(ctx, q.deleteExerciseStmt, deleteExercise, arg.ID, arg.UserID)
	return err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, muscle_group, category, isstock, most_weight_lifted, most_reps_lifted, rest_timer, user_id FROM exercise
WHERE id = ? AND user_id = UUID_TO_BIN(?) LIMIT 1
`

type GetExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetExercise(ctx context.Context, arg GetExerciseParams) (Exercise, error) {
	row := q.queryRow(ctx, q.getExerciseStmt, getExercise, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MuscleGroup,
		&i.Category,
		&i.Isstock,
		&i.MostWeightLifted,
		&i.MostRepsLifted,
		&i.RestTimer,
		&i.UserID,
	)
	return i, err
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name, muscle_group, category, isstock, most_weight_lifted, most_reps_lifted, rest_timer, user_id FROM exercise
WHERE name = ? AND user_id = UUID_TO_BIN(?)
`

type GetExerciseByNameParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetExerciseByName(ctx context.Context, arg GetExerciseByNameParams) (Exercise, error) {
	row := q.queryRow(ctx, q.getExerciseByNameStmt, getExerciseByName, arg.Name, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MuscleGroup,
		&i.Category,
		&i.Isstock,
		&i.MostWeightLifted,
		&i.MostRepsLifted,
		&i.RestTimer,
		&i.UserID,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, muscle_group, category, isstock, most_weight_lifted, most_reps_lifted, rest_timer, user_id FROM exercise
WHERE user_id = UUID_TO_BIN(?)
`

func (q *Queries) ListExercises(ctx context.Context, userID string) ([]Exercise, error) {
	rows, err := q.query(ctx, q.listExercisesStmt, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MuscleGroup,
			&i.Category,
			&i.Isstock,
			&i.MostWeightLifted,
			&i.MostRepsLifted,
			&i.RestTimer,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :exec
UPDATE exercise SET
	name = COALESCE(?, name),
	muscle_group = COALESCE(?, muscle_group),
	category = COALESCE(?, category),
	most_weight_lifted = COALESCE(?, most_weight_lifted),
	most_reps_lifted = COALESCE(?, most_reps_lifted),
	rest_timer = COALESCE(?, rest_timer)
WHERE user_id = UUID_TO_BIN(?) AND id = ?
`

type UpdateExerciseParams struct {
	Name             sql.NullString  `json:"name"`
	MuscleGroup      sql.NullString  `json:"muscle_group"`
	Category         sql.NullString  `json:"category"`
	MostWeightLifted sql.NullFloat64 `json:"most_weight_lifted"`
	MostRepsLifted   sql.NullInt32   `json:"most_reps_lifted"`
	RestTimer        sql.NullString  `json:"rest_timer"`
	UserID           string          `json:"user_id"`
	ID               int32           `json:"id"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) error {
	_, err := q.exec(ctx, q.updateExerciseStmt, updateExercise,
		arg.Name,
		arg.MuscleGroup,
		arg.Category,
		arg.MostWeightLifted,
		arg.MostRepsLifted,
		arg.RestTimer,
		arg.UserID,
		arg.ID,
	)
	return err
}
