// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: inactive.sql

package db

import (
	"context"
)

const getInactiveUser = `-- name: GetInactiveUser :one
SELECT BIN_TO_UUID(id) AS id FROM
` + "`" + `inactive_user` + "`" + ` WHERE id = UUID_TO_BIN(?)
`

func (q *Queries) GetInactiveUser(ctx context.Context, userID string) (string, error) {
	row := q.queryRow(ctx, q.getInactiveUserStmt, getInactiveUser, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}
