// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"
)

const createProfile = `-- name: CreateProfile :execresult
INSERT INTO profile (
	country,
	measurement_system,
	body_weight,
	body_fat,
	timezone,
	user_id
) VALUES (?, ?, ?, ?, ?, UUID_TO_BIN(?))
`

type CreateProfileParams struct {
	Country           string  `json:"country"`
	MeasurementSystem string  `json:"measurement_system"`
	BodyWeight        float64 `json:"body_weight"`
	BodyFat           float64 `json:"body_fat"`
	Timezone          string  `json:"timezone"`
	UserID            string  `json:"user_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (sql.Result, error) {
	return q.exec(ctx, q.createProfileStmt, createProfile,
		arg.Country,
		arg.MeasurementSystem,
		arg.BodyWeight,
		arg.BodyFat,
		arg.Timezone,
		arg.UserID,
	)
}

const deleteProfile = `-- name: DeleteProfile :execresult
DELETE FROM profile
WHERE user_id = UUID_TO_BIN(?)
`

func (q *Queries) DeleteProfile(ctx context.Context, userID string) (sql.Result, error) {
	return q.exec(ctx, q.deleteProfileStmt, deleteProfile, userID)
}

const getProfile = `-- name: GetProfile :one
SELECT id, country, measurement_system, body_weight, body_fat, timezone, user_id FROM profile
WHERE user_id = UUID_TO_BIN(?) LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, userID string) (Profile, error) {
	row := q.queryRow(ctx, q.getProfileStmt, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.MeasurementSystem,
		&i.BodyWeight,
		&i.BodyFat,
		&i.Timezone,
		&i.UserID,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :execresult
UPDATE profile SET
country = IFNULL(?, country),
measurement_system = IFNULL(?, measurement_system),
body_weight = IFNULL(?, body_weight),
body_fat = IFNULL(?, body_fat),
timezone = IFNULL(?, timezone)
WHERE user_id = UUID_TO_BIN(?)
`

type UpdateProfileParams struct {
	Country           interface{} `json:"country"`
	MeasurementSystem interface{} `json:"measurement_system"`
	BodyWeight        interface{} `json:"body_weight"`
	BodyFat           interface{} `json:"body_fat"`
	Timezone          interface{} `json:"timezone"`
	UserID            string      `json:"user_id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (sql.Result, error) {
	return q.exec(ctx, q.updateProfileStmt, updateProfile,
		arg.Country,
		arg.MeasurementSystem,
		arg.BodyWeight,
		arg.BodyFat,
		arg.Timezone,
		arg.UserID,
	)
}
