// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const changePassword = `-- name: ChangePassword :exec
UPDATE user SET
password = ?,
password_changed_at = NOW()
WHERE id = UUID_TO_BIN(?)
`

type ChangePasswordParams struct {
	Password string `json:"password"`
	UserID   string `json:"user_id"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.exec(ctx, q.changePasswordStmt, changePassword, arg.Password, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO user (
	id,
	first_name,
	last_name,
	email_address,
	password
) VALUES (UUID_TO_BIN(UUID()),?, ?, ?, ?)
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	EmailAddress string `json:"email_address"`
	Password     string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.Password,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user
WHERE id = UUID_TO_BIN(?)
`

func (q *Queries) DeleteUser(ctx context.Context, uuidTOBIN string) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, uuidTOBIN)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT BIN_TO_UUID(id) as id, first_name, last_name, email_address, password_changed_at, password
FROM user WHERE email_address = ? LIMIT 1
`

type GetUserByEmailRow struct {
	ID                string    `json:"id"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	EmailAddress      string    `json:"email_address"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Password          string    `json:"password"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, emailAddress)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.PasswordChangedAt,
		&i.Password,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT BIN_TO_UUID(id) as id, first_name, last_name, email_address, password_changed_at, password
FROM user WHERE id = UUID_TO_BIN(?) LIMIT 1
`

type GetUserByIdRow struct {
	ID                string    `json:"id"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	EmailAddress      string    `json:"email_address"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Password          string    `json:"password"`
}

func (q *Queries) GetUserById(ctx context.Context, userID string) (GetUserByIdRow, error) {
	row := q.queryRow(ctx, q.getUserByIdStmt, getUserById, userID)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.PasswordChangedAt,
		&i.Password,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user SET
	first_name = COALESCE(?, first_name),
	last_name = COALESCE(?, last_name),
	email_address = COALESCE(?, email_address)
WHERE id = UUID_TO_BIN(?)
`

type UpdateUserParams struct {
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	EmailAddress sql.NullString `json:"email_address"`
	UserID       string         `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.UserID,
	)
	return err
}
