name: Unit Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql
        ports: 
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: secret 
          MYSQL_DATABASE: ismogged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        env: 
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: secret
          MYSQL_DBNAME: ismogged
        run: make migrateup

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test