name: Go Unit Test with MySQL and Migrate

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: ismogged
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        
    - name: Set up MySQL
      run: |
        make dbcontainer
        make createdb
        make migrateup
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      env:
        DB_PORT: 3306
        DB_URL: "localhost:3306/ismogged?parseTime=true"
      run: |
        go test -v -cover ./...
